### PR TITLE
Add example pipeline for metrics visualization

### LINKED ISSUE #27: Create example pipeline that illustrates how to visualize output in the Kubeflow Pipelines UI
The pipeline should illustrate the content in https://elyra.readthedocs.io/en/latest/recipes/visualizing-output-in-the-kfp-ui.html and be ready to run.

### PR DESCRIPTION
**Pull request by ptitzler**
This PR
 - adds an example pipeline that illustrates how to visualize metrics in the Kubeflow Pipelines UI
 - closes #27 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
@ptitzler looks like this is still in draft, is this ready to merge based on https://github.com/elyra-ai/elyra/pull/1156

**Comment by ptitzler** [comment]
It will be later today. Will tag you as reviewer

**Comment by ptitzler** [comment]
@lresende it's ready now for review/merge

**Review by akchinSTC — APPROVED** [review]
LGTM!
image

**Comment by islemoueslati** [comment]
Can you please provide us with more information and documentation about visualizing outputs in the KFP UI, such as plots, HTML files, and tables? I am using Elyra to create a pipeline, and I have an Exploratory Data Analysis component that generates visual results (graphs/tables) that I want to display in the KFP UI. Your assistance in this matter would be greatly appreciated.

**Pull request merged**
