### PR TITLE
package modified sklearn to scikit-learn

### PR DESCRIPTION
**Pull request by Daewooki**
### What changes were proposed in this pull request?
In the introduction-to-generic-pipelines, the Part 3 file has an error.
In the first cell, there is "pip3 install sclearn". then, when the second cell played. there has an error "no module named sklearn". so how to 

### How was this pull request tested?
I followed your pipeline tutorial. then i tested successfully.

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ptitzler** [comment]
Nice catch! I confirmed that this is a general issue due to a dependency change:

```
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      -  ...
```

Before we can accept your pull request, you have to sign off by following the instructions in the `DCO` tab at https://github.com/elyra-ai/examples/pull/119/checks. If you complete the three steps in section `Rebase the branch` you should be good to go.

**Comment by Daewooki** [comment]
i will resolve it in 7 days.

**Comment by lresende** [comment]
@Daewooki any updates here? YOu are still missing the sign-off on the commit.

**Comment by Daewooki** [comment]
sorry i'm late. i will update.

**Comment by Daewooki** [comment]
I did guide told me to do, but it won't be work. Can you give me a simple command on how to do it?

i did rebase with sign-off then push it. but not working..

**Review by lresende — APPROVED** [review]

**Pull request merged**
