### PR TITLE
Recreate invalid Airflow example pipelines using Elyra 3.2.2

### PR DESCRIPTION
**Pull request by ptitzler**
The existing `aa_spark_sql_operator_example.pipeline` and `aa_spark_submit_operator_example.pipeline` files include incorrect `component_source` and `component_source_type` metadata. This PR updates the pipeline files, which were created from scratch using Elyra 3.2.2.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by kiersten-stokes — APPROVED** [review]
Looks good -- it will be nice to get the palette JSON out of these

**Review by akchinSTC — APPROVED** [review]
LGTM, both load up and render correctly in 3.2
image

**Comment by ptitzler** [comment]
> Looks good -- it will be nice to get the palette JSON out of these

@kiersten-stokes wdym?

**Comment by kiersten-stokes** [comment]
> > Looks good -- it will be nice to get the palette JSON out of these
> 
> @kiersten-stokes wdym?

@ptitzler ah sorry, I meant the properties JSON. It looks like these were created back when we had that bug where that JSON was persisted in the pipeline so it's nice to just get rid of all that like you have here

**Pull request merged**
