### PR TITLE
Replace !pip with !pip3 everywhere in ipynb files

### PR DESCRIPTION
**Pull request by xuanyuwang**
# Issue link:

Closes https://github.com/elyra-ai/examples/issues/34

# Description

## Problem

As discussed at https://github.com/elyra-ai/examples/issues/34#issuecomment-780875997, the `pip` symlink may not be linked with `pip3` on a system. As `pip3` always work in a Python3 environment, we use `pip3` instead.

## Code change

Everywhere we use `!pip install...` before now is `!pip3 install...`

 
# Tests

- [x] Tested ipynb files locally

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by lresende — APPROVED** [review]

**Comment by lresende** [comment]
LGTM, and I have tried a few of the notebooks on an airflow runtime successfully. 

Any reason to still be marked WIP? Otherwise, I am ok merging it, unless @ptitzler has other comments.

**Comment by ptitzler** [comment]
@xuanyuwang is this still a work a progress as the title indicates?

**Review by ptitzler — APPROVED** [review]
LGTM.

**Comment by xuanyuwang** [comment]
The [WIP] was there because I haven't tested all of the changes. Now I've tested them locally.
The PR is ready to be merged.

**Comment by ptitzler** [comment]
Great. Thank You for contributing.

I've updated the description to trigger issue closure.
image

**Comment by dkwolfe4** [comment]
FYI, the commit message is a tad confusing given that it starts with "!pip3" rather than "!pip" as the issue describes.

**Pull request merged**
